-- Create temp_publications table
CREATE TABLE IF NOT EXISTS `temp_publications` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name` varchar(255) DEFAULT NULL,
    `title` varchar(255) DEFAULT NULL,
    `description` text DEFAULT NULL,
    `original_filename` varchar(255) NOT NULL,
    `file_path` varchar(255) NOT NULL,
    `file_url` varchar(255) DEFAULT NULL,
    `mime_type` varchar(255) DEFAULT NULL,
    `file_size` bigint(20) DEFAULT NULL,
    `year` int(11) DEFAULT NULL,
    `month` int(11) DEFAULT NULL,
    `day` int(11) DEFAULT NULL,
    `page` int(11) DEFAULT NULL,
    `user_id` bigint(20) unsigned NOT NULL,
    `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    `admin_notes` text DEFAULT NULL,
    `verified_by` bigint(20) unsigned DEFAULT NULL,
    `verified_at` timestamp NULL DEFAULT NULL,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `temp_publications_user_id_foreign` (`user_id`),
    KEY `temp_publications_verified_by_foreign` (`verified_by`),
    KEY `temp_publications_status_created_at_index` (`status`, `created_at`),
    KEY `temp_publications_user_id_status_index` (`user_id`, `status`),
    CONSTRAINT `temp_publications_user_id_foreign` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `temp_publications_verified_by_foreign` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
