<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Activities Report - {{ $date }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        h1 { font-size: 18px; text-align: center; margin-bottom: 20px; }
        .header { margin-bottom: 20px; }
        .footer { margin-top: 30px; font-size: 10px; text-align: center; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background-color: #f5f5f5; text-align: left; padding: 8px; border: 1px solid #ddd; }
        td { padding: 8px; border: 1px solid #ddd; }
        .filters { margin-bottom: 20px; }
        .filter-item { margin-bottom: 5px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Activities Report</h1>
        <div class="filters">
            <div class="filter-item"><strong>Generated on:</strong> {{ $date }}</div>
            @if(!empty($filters['type']))
                <div class="filter-item"><strong>Type:</strong> {{ ucfirst($filters['type']) }}</div>
            @endif
            @if(!empty($filters['date_from']) || !empty($filters['date_to']))
                <div class="filter-item">
                    <strong>Date Range:</strong> 
                    {{ !empty($filters['date_from']) ? $filters['date_from'] : 'Start' }} 
                    to 
                    {{ !empty($filters['date_to']) ? $filters['date_to'] : 'End' }}
                </div>
            @endif
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Type</th>
                <th>Title</th>
                <th>Description</th>
                <th>Date</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            @foreach($activities as $activity)
                <tr>
                    <td>{{ ucfirst($activity['type']) }}</td>
                    <td>{{ $activity['title'] }}</td>
                    <td>{{ $activity['description'] }}</td>
                    <td>{{ \Carbon\Carbon::parse($activity['timestamp'])->format('Y-m-d H:i:s') }}</td>
                    <td>
                        @if(isset($activity['details']))
                            @foreach($activity['details'] as $key => $value)
                                <div><strong>{{ $key }}:</strong> {{ $value }}</div>
                            @endforeach
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Library Management System - {{ date('Y') }}
    </div>
</body>
</html>
